### ISSUE TITLE
First version of the UI 

### ISSUE THREAD

**Issue by baptation** [sigurdskatvedt/projet-programmation-web#10]
I don't know where in GitHub I am supposed to say when I did something, but here I do : I did a first version of the UI which you can edit with the link I sent on your email. (The following one only allows you to see it but not to edit it for some reason ...) 
https://www.figma.com/file/bgY5trT3XBj9tPmoZx1ioT/UI-Projet-DEVWEB?node-id=0%3A1
Don't hesitate to change it of course ! 
![goku-ssj](https://user-images.githubusercontent.com/97606451/200412773-4221d45d-05f9-4edd-b658-1d1dea11f7fa.gif)

**Comment by sigurdskatvedt** [comment]
Let's gooo! Looks so good🤩 You should work as a UX designer🫶🤝
